#!/usr/bin/env bash
# Work around a packaging bug in stasel/WebRTC (v149): the macOS slice of the
# distributed XCFramework ships only the umbrella WebRTC.h and is missing every
# per-class header, so `import WebRTC` cannot build the module on macOS.
#
# The macOS *dylib* is complete. The core Objective-C headers we use
# (RTCPeerConnection, RTCVideoSource, the VideoToolbox encoder factory, …) are
# platform-independent, so we copy them from the complete ios-arm64 slice. We
# deliberately EXCLUDE the iOS-only headers (UIKit views, EAGL, AVAudioSession),
# which reference symbols that don't exist on macOS, and regenerate a curated
# umbrella header that imports only what remains.
#
# Idempotent. Re-run after `swift package clean` (which re-extracts the artifact).
set -euo pipefail

XCF="$(find .build/artifacts -type d -iname 'WebRTC.xcframework' 2>/dev/null | head -1)"
if [[ -z "${XCF}" ]]; then
  echo "WebRTC.xcframework not found under .build/artifacts — run 'swift package resolve' first." >&2
  exit 1
fi

SRC="${XCF}/ios-arm64/WebRTC.framework/Headers"
DST="${XCF}/macos-x86_64_arm64/WebRTC.framework/Versions/A/Headers"

# iOS-only headers reference symbols absent on macOS (UIKit views, OpenGLES/EAGL,
# AVAudioSession, UIDevice, …). We use none of them — no local rendering, no
# audio session on the desktop — so any header touching these is dropped. The
# umbrella (WebRTC.h) is always regenerated. Detection is by content match so we
# don't have to maintain a hand-curated list as upstream adds headers.
IOS_ONLY_PATTERN='UIKit/UIKit|OpenGLES|<GLKit|EAGL|AVAudioSession|UIView|UIDevice|UIInterfaceOrientation|UIImage|UIScreen'

is_excluded() {
  local file="$1" name
  name="$(basename "$file")"
  [[ "$name" == "WebRTC.h" ]] && return 0
  grep -Eq "$IOS_ONLY_PATTERN" "$file" && return 0
  return 1
}

if [[ ! -d "${SRC}" ]]; then
  echo "Source iOS headers not found at ${SRC}" >&2
  exit 1
fi

mkdir -p "${DST}"
# Start clean so removing an entry from EXCLUDE can't leave a stale header behind.
find "${DST}" -name '*.h' -delete

umbrella="${DST}/WebRTC.h"
{
  echo "// Curated macOS umbrella generated by scripts/patch-webrtc-headers.sh"
  echo "#import <Foundation/Foundation.h>"
} > "${umbrella}"

count=0
excluded=0
for h in "${SRC}"/*.h; do
  name="$(basename "$h")"
  if is_excluded "$h"; then excluded=$((excluded + 1)); continue; fi
  cp "$h" "${DST}/"
  echo "#import <WebRTC/${name}>" >> "${umbrella}"
  count=$((count + 1))
done

echo "Patched macOS WebRTC headers: ${count} imported, ${excluded} iOS-only excluded."
